%% CT runners for erlang_standard_SUITE.
email(Config) -> liver_ct_cases:run(email, Config).
iso_date(Config) -> liver_ct_cases:run(iso_date, Config).
livr_name_unavailable(Config) -> liver_ct_cases:run(livr_name_unavailable, Config).
is_integer_under_livr_spec(Config) -> liver_ct_cases:run(is_integer_under_livr_spec, Config).
is_integer(Config) -> liver_ct_cases:run(is_integer, Config).
is_string(Config) -> liver_ct_cases:run(is_string, Config).
is_utf8_binary(Config) -> liver_ct_cases:run(is_utf8_binary, Config).
is_atom(Config) -> liver_ct_cases:run(is_atom, Config).
is_float(Config) -> liver_ct_cases:run(is_float, Config).
is_number(Config) -> liver_ct_cases:run(is_number, Config).
is_non_neg_integer(Config) -> liver_ct_cases:run(is_non_neg_integer, Config).
is_pos_integer(Config) -> liver_ct_cases:run(is_pos_integer, Config).
to_integer(Config) -> liver_ct_cases:run(to_integer, Config).
to_float(Config) -> liver_ct_cases:run(to_float, Config).
to_utf8_binary(Config) -> liver_ct_cases:run(to_utf8_binary, Config).
to_existing_atom(Config) -> liver_ct_cases:run(to_existing_atom, Config).
to_map(Config) -> liver_ct_cases:run(to_map, Config).
to_proplist(Config) -> liver_ct_cases:run(to_proplist, Config).
one_of_terms(Config) -> liver_ct_cases:run(one_of_terms, Config).
range(Config) -> liver_ct_cases:run(range, Config).
byte_size(Config) -> liver_ct_cases:run(byte_size, Config).
length(Config) -> liver_ct_cases:run(length, Config).
is_tuple(Config) -> liver_ct_cases:run(is_tuple, Config).
email_ascii(Config) -> liver_ct_cases:run(email_ascii, Config).
email_unicode(Config) -> liver_ct_cases:run(email_unicode, Config).
iso_date_binary(Config) -> liver_ct_cases:run(iso_date_binary, Config).
iso_date_tuple(Config) -> liver_ct_cases:run(iso_date_tuple, Config).
nested_map(Config) -> liver_ct_cases:run(nested_map, Config).
rule_set_livr_spec(Config) -> liver_ct_cases:run(rule_set_livr_spec, Config).
rule_set_compose(Config) -> liver_ct_cases:run(rule_set_compose, Config).
rule_set_mixed_alias(Config) -> liver_ct_cases:run(rule_set_mixed_alias, Config).
