name: Liver build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    ## Every Monday at 2am.
    - cron: 0 2 * * 1

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Liver
    if: ${{ !cancelled() }}
    uses: erlangbureau/ci.erlang.mk/.github/workflows/ci.yaml@master
